# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-05 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questionnaire', '0001_initial'),
        ('institutions', '__first__'),
        ('exploration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionExplorationRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(verbose_name='Total points')),
                ('collected_points', models.IntegerField(verbose_name='Collected points')),
                ('exploration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exploration.Exploration')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_rates', to='institutions.Institution')),
            ],
            options={
                'verbose_name': "Institution's rate",
                'verbose_name_plural': 'Institutions rates',
            },
        ),
        migrations.CreateModel(
            name='InstitutionGroupRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_points', models.IntegerField(verbose_name='Total points')),
                ('collected_points', models.IntegerField(verbose_name='Collected points')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_rates', to='questionnaire.Group')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='institutions.Institution')),
            ],
            options={
                'verbose_name': "Groups's rates",
                'verbose_name_plural': 'Institutions assessments',
            },
        ),
        migrations.AlterUniqueTogether(
            name='institutiongrouprate',
            unique_together=set([('institution', 'group')]),
        ),
        migrations.AlterUniqueTogether(
            name='institutionexplorationrate',
            unique_together=set([('institution', 'exploration')]),
        ),
    ]
