# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-18 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutiongrouprate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups_rates', to='questionnaire.Group'),
        ),
        migrations.AlterField(
            model_name='institutiongrouprate',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='institutions.Institution'),
        ),
        migrations.AlterField(
            model_name='institutionrankingrate',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_rates', to='institutions.Institution'),
        ),
    ]
