# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-05 05:33
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import raporty_siecobywatelska_pl.articles.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=raporty_siecobywatelska_pl.articles.models.populate_slug, unique=True, verbose_name='Slug')),
                ('short_description', models.TextField(verbose_name='Short description')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('exploration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exploration.Exploration')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['name'],
            },
        ),
    ]
