# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-09 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exploration',
            name='for_exclusive_group',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exploration',
            name='requirement_of_credibility',
            field=models.IntegerField(default=200),
        ),
    ]
