# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-23 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exploration', '0002_auto_20190109_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exploration',
            name='for_exclusive_group',
        ),
    ]
