# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranking.Ranking')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Question groups',
                'verbose_name': 'Question group',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Group')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name_plural': 'Question',
                'verbose_name': 'Question',
            },
        ),
    ]
