# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-05 05:33
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exploration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Slug')),
                ('exploration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exploration.Exploration')),
            ],
            options={
                'verbose_name': 'Question group',
                'verbose_name_plural': 'Question groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Group')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Question',
                'ordering': ['name'],
            },
        ),
    ]
