# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-26 15:04
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True, verbose_name='Slug')),
                ('description', models.TextField()),
                ('institutions', models.ManyToManyField(blank=True, related_name='rankings', to='institutions.Institution')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': 'Ranking',
                'verbose_name_plural': 'Rankings',
            },
        ),
    ]
