# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-05 05:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teryt_tree', '0004_auto_20170712_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='JST',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('teryt_tree.jednostkaadministracyjna',),
        ),
    ]
