# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-25 22:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teryt_tree', '0004_auto_20170712_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='JST',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('teryt_tree.jednostkaadministracyjna',),
        ),
    ]
