# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-09 04:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersCredibilityPoints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('point', models.IntegerField()),
                ('exploration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='institutions.Institution')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='institutions.Institution')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='score_of_credibility',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='answerscredibilitypoints',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='answerscredibilitypoints',
            unique_together=set([('user', 'institution', 'exploration')]),
        ),
    ]
