# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-18 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_initially_introduced',
            field=models.BooleanField(default=False, verbose_name='It is initially introduced'),
        ),
    ]
