# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-23 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190109_0456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerscredibilitypoints',
            name='exploration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exploration.Exploration'),
        ),
    ]
